# Generated by Django 2.2.1 on 2019-09-12 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_datetime', models.DateTimeField()),
                ('measurement_type', models.CharField(max_length=100)),
                ('measurement_value', models.TextField()),
                ('participant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.Participant')),
            ],
            options={
                'unique_together': {('participant_id', 'measurement_datetime', 'measurement_type')},
            },
        ),
    ]
