# Generated by Django 2.2.1 on 2019-08-22 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concentration', models.FloatField()),
                ('aqi', models.FloatField(verbose_name='air quality index')),
                ('measurement_time', models.DateTimeField()),
            ],
        ),
    ]
