# Generated by Django 2.2.1 on 2019-09-06 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ID_Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name/label/id of the subject')),
            ],
        ),
        migrations.CreateModel(
            name='Thermal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name/label/id of the subject')),
                ('temperature', models.FloatField()),
                ('rh', models.FloatField()),
                ('measurement_time', models.DateTimeField()),
                ('id_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.ID_Label')),
            ],
        ),
        migrations.CreateModel(
            name='SleepSurveys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name/label/id of the subject')),
                ('time_asleep', models.FloatField(verbose_name='minutes spent in REM or Non-REM')),
                ('restful', models.IntegerField(verbose_name='Likert Scale value for how restful the user thought their sleep was')),
                ('refreshed', models.IntegerField(verbose_name='Likert Scale value for how refreshed the user thought their sleep was')),
                ('aggregate', models.FloatField(verbose_name='Sum of time_asleep, restful score, and refreshed score')),
                ('normalized', models.FloatField(verbose_name='Normalized sleep score')),
                ('night', models.DateTimeField()),
                ('count', models.IntegerField(verbose_name='number of datapoints averaged to create the metrics')),
                ('id_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.ID_Label')),
            ],
        ),
        migrations.CreateModel(
            name='SleepMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name/label/id of the subject')),
                ('time_asleep', models.FloatField(verbose_name='minutes spent in REM or Non-REM')),
                ('awake', models.FloatField(verbose_name='percentage of time spent awake')),
                ('rem', models.FloatField(verbose_name='percentage of time spent in REM')),
                ('nrem', models.FloatField(verbose_name='percentage of tiem spent in Non-REM')),
                ('latency', models.FloatField(verbose_name='number of minutes awake before falling asleep')),
                ('efficiency', models.FloatField(verbose_name='percentage of time spent asleep while in bed')),
                ('night', models.DateTimeField()),
                ('count', models.IntegerField(verbose_name='number of datapoints averaged to create the metrics')),
                ('id_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.ID_Label')),
            ],
        ),
        migrations.CreateModel(
            name='PM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name/label/id of the subject')),
                ('concentration', models.FloatField()),
                ('aqi', models.FloatField(verbose_name='air quality index')),
                ('measurement_time', models.DateTimeField()),
                ('id_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm.ID_Label')),
            ],
        ),
    ]
