# Generated by Django 2.2.1 on 2019-08-22 13:21

from django.db import migrations

import pandas as pd

def importInitialData(apps, schema_editor):
	PM = apps.get_model('pm','PM')
	path = "~/Google Drive/Research/5_Sensors/Projects/UT2000-SummerDashboard/Code_Development/Files/uuc9c1q8_IAQ.csv"
	raw_data = pd.read_csv(path,header=None,skiprows=1,usecols=[3,4,5],names=['Concentration','AQI','Time'])
	for i in range(len(raw_data)):
		obj, created = PM.objects.get_or_create(
			concentration = raw_data['Concentration'][i],
			aqi = raw_data['AQI'][i],
			measurement_time = raw_data['Time'][i]
			)


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0001_initial'),
    ]

    operations = [
    	migrations.RunPython(importInitialData),
    ]
